### ISSUE TITLE
Remove alpha bar

### ISSUE THREAD

**Issue by jonnydevv** [mjolnic/bootstrap-colorpicker#131]
Hello!

Is it possible to remove alpha bar?

**Comment by mjolnic** [comment]
@jonnydevv the alpha bar appears only when your color format supports alpha. there is no method to hide it. so you need to do it in your own code.

**Comment by Shogun147** [comment]
+1 for this, any solution?

**Comment by icewer** [comment]
This worked for me. Add to css styles:

`.colorpicker-alpha {display:none !important;}
.colorpicker{ min-width:128px !important;}`

Just take in mind this **ALWAYS** hides the _alpha-bar_, so if you want to enable/disable it, you would have to make an independent class rule (and add/remove it via jQuery or other methods).

**Comment by mjolnic** [comment]
You can also customize the widget template and remove the alpha bar:

https://github.com/mjolnic/bootstrap-colorpicker/blob/master/src/js/colorpicker-defaults.js#L55

**Comment by paresh** [comment]
rather than changing inside library you could set Options inside colorpicker.

`var template = '<div class="colorpicker dropdown-menu">' +
        '<div class="colorpicker-saturation"><i><b></b></i></div>' +
        '<div class="colorpicker-hue"><i></i></div>' +
        '<div class="colorpicker-color"><div /></div>' +
        '<div class="colorpicker-selectors"></div>' +
        '</div>';
colorpicker({template})
`

**Comment by paresh** [comment]
rather than changing inside library file. better change it parameter
`      var template = '<div class="colorpicker dropdown-menu">' +`
`        '<div class="colorpicker-saturation"><i><b></b></i></div>' +`
`        '<div class="colorpicker-hue"><i></i></div>' +`
`        '<div class="colorpicker-color"><div /></div>' +`
`        '<div class="colorpicker-selectors"></div>' +  '</div>';`

`$('.sample-selector').colorpicker({ template });`
